[workspace.package]
edition = "2021"
repository = "https://github.com/Lut99/k-shortest-paths"


[workspace]
resolver = "2"
members = [
    "ksp-alg",
    "ksp-bench",
    "ksp-graph",
    "ksp-pip",
    "ksp-vis"
]
